### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by xDrFakeDevSimba** [pizdo/nagroda-minecraft#3]
The plugin is enabled but the command does not run
Error in console:
[15:12:40 WARN]: [RewardPlugin] Task #479 for RewardPlugin v1.0-SNAPSHOT generated an exception
java.lang.NullPointerException
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-PaperSpigot-"8b18730"]
at net.wajwuz.discord.command.impl.AwardCommand$1.run(AwardCommand.java:87) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

Engine: Paperspigot

**Comment by pizdo** [comment]
use new version
